# Generated by Django 4.2 on 2023-04-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(default='', max_length=50, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='', max_length=20, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(max_length=20, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.IntegerField(default=1000, verbose_name='Rating'),
        ),
    ]
