# Generated by Django 4.2 on 2023-05-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='system',
            field=models.CharField(choices=[('swiss', 'Swiss System'), ('robin', 'Round-robin System')], default='swiss', max_length=5, verbose_name='System'),
        ),
    ]
