# Generated by Django 4.2 on 2023-04-26 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_player_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6, verbose_name='Gender'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('place', models.CharField(max_length=30, verbose_name='Place')),
                ('description', models.TextField(verbose_name='Description')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('date_of_start', models.DateTimeField(verbose_name='Start')),
                ('date_of_end', models.DateTimeField(verbose_name='End')),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10, verbose_name='Time control')),
                ('result', models.CharField(max_length=10, verbose_name='Result')),
                ('date', models.DateTimeField(verbose_name='Start game')),
                ('players', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
