# Generated by Django 4.2 on 2023-05-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='password2',
            field=models.CharField(default='', max_length=128, verbose_name='Password'),
        ),
    ]
