# Generated by Django 4.2 on 2023-05-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_player_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='opened',
            field=models.BooleanField(default=True, verbose_name='Registration'),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.IntegerField(default=1000, verbose_name='Rating'),
        ),
    ]
