# Generated by Django 4.2 on 2023-05-03 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_organizer_tournament_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='organizer',
        ),
        migrations.AddField(
            model_name='tournament',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
    ]
