# Generated by Django 4.2 on 2023-05-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_player_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='unique_id',
            field=models.CharField(default='default_value', max_length=16, unique=True),
        ),
    ]
