# Generated by Django 4.2 on 2023-05-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_player_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='unique_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
