# Generated by Django 4.2 on 2023-05-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_player_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='gender',
        ),
    ]
