# Generated by Django 4.2 on 2023-05-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_player_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='unique_id',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
    ]
