# Generated by Django 4.2 on 2023-05-17 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_player_language_player_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='language',
            new_name='lang',
        ),
    ]
