# Generated by Django 4.2 on 2023-05-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_language_player_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='player',
            name='theme',
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='player_photos/'),
        ),
    ]
