# Generated by Django 4.2 on 2023-05-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, default='static/images/no_foto.jpg', null=True, upload_to='images/foto/'),
        ),
    ]
